#spring:
#  application:
#    name: user
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/mydb
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#      base-path: /manage


# Adding all the required dependencies for postgre sql

spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=admin
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true